version: 0.2

phases:
  install:
    commands:
      - echo "Installing packages..."
  build:
    commands:
      - echo "Building the application..."
  post_build:
    commands:
      - echo "Deployment phase..."

artifacts:
  files:
    - index.html
